-- Sample data migration from legacy memdic table to new slia_members table

INSERT INTO `slia_members` (
  `full_name`,
  `name_with_initials`,
  `nic_number`,
  `gender`,
  `date_of_birth`,
  `academic_qualifications`,
  `professional_qualifications`,
  `membership_type`,
  `membership_number`,
  `membership_year`,
  `arb_number`,
  `practice_name`,
  `practice_description`,
  `practice_type`,
  `location_district`,
  `location_province`,
  `office_address`,
  `office_phone`,
  `office_fax`,
  `office_email`,
  `office_website`,
  `home_address`,
  `home_phone`,
  `home_fax`,
  `home_email`,
  `contact_info_1_address`,
  `contact_info_1_phone`,
  `contact_info_1_email`,
  `positions_held`,
  `slia_awards`,
  `other_awards`,
  `username`,
  `password`,
  `created_at`,
  `updated_at`
) VALUES (
  'Hemantha Bandula Wijewardanee',
  'ARCHT. H B WIJEWARDANE',
  NULL,
  'Female',
  NULL,
  'M.Env.Planning, M.Sc.(Arch.), B.Sc.(BE)',
  'AIA(SL) 1987, ARAIA, MPIA',
  'Associate Member',
  'A0145',
  '2023',
  'CA98052',
  NULL,
  NULL,
  NULL,
  'Colombo',
  NULL,
  '42/1, Ananda Coomaraswamy Mawatha, Colombo 07.',
  NULL,
  NULL,
  NULL,
  NULL,
  '42/1, Ananda Coomaraswamy Mawatha, Colombo 07.',
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  NULL,
  'A0145889',
  'A0145889',
  NOW(),
  NOW()
);
